services:
  localstack:
    image: localstack/localstack
    platform: linux/arm64
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
